# Generated by scripts/audit_rideable.py — do not edit by hand.
# Gives every rideable Gen1 Pokemon (48 total) to the executor at level 50.
# First 6 land in the party; the rest overflow into the PC automatically.
# Run with: /function gen1ify:test_rideable
tellraw @s [{"text":"Adding 48 rideable Gen1 Pokemon to your party + PC...","color":"gold"}]
pokegive aerodactyl level=50
pokegive alakazam level=50
pokegive arcanine level=50
pokegive articuno level=50
pokegive beedrill level=50
pokegive blastoise level=50
pokegive butterfree level=50
pokegive charizard level=50
pokegive dewgong level=50
pokegive ditto level=50
pokegive dodrio level=50
pokegive dragonair level=50
pokegive dragonite level=50
pokegive dratini level=50
pokegive electrode level=50
pokegive exeggutor level=50
pokegive fearow level=50
pokegive golem level=50
pokegive graveler level=50
pokegive gyarados level=50
pokegive jigglypuff level=50
pokegive kangaskhan level=50
pokegive lapras level=50
pokegive machamp level=50
pokegive machoke level=50
pokegive mew level=50
pokegive mewtwo level=50
pokegive moltres level=50
pokegive mrmime level=50
pokegive nidoqueen level=50
pokegive omastar level=50
pokegive onix level=50
pokegive parasect level=50
pokegive pidgeot level=50
pokegive pidgeotto level=50
pokegive rapidash level=50
pokegive rhydon level=50
pokegive rhyhorn level=50
pokegive seaking level=50
pokegive snorlax level=50
pokegive starmie level=50
pokegive staryu level=50
pokegive tauros level=50
pokegive venomoth level=50
pokegive venusaur level=50
pokegive weezing level=50
pokegive wigglytuff level=50
pokegive zapdos level=50
tellraw @s [{"text":"Done. First 6 are in your party; swap from the PC to test the rest.","color":"green"}]
